[package]
name = "gnip_simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
chrono = "0.4.37"
clap = { version = "4.5.4", features = ["derive"] }
statrs = "0.16.0"
indicatif = "0.17.8"
prettytable-rs = "0.10.0"
itertools = "0.12.1"
rayon = "1.10.0"
rustc-hash = "1.1.0"
